

--Q1. What is the total revenue generated by each gender?
SELECT gender, 
SUM(purchase_amount) AS revenue
FROM Customers
GROUP BY gender
ORDER BY gender ASC




--Q2. Which product categories generate the most revenue?
SELECT 
    category,
    SUM(purchase_amount) AS Total_Sales
FROM Customers
GROUP BY category
ORDER BY Total_Sales DESC;




--Q3. Which items are purchased most frequently?
SELECT TOP 5
    item_purchased,
    COUNT(*) AS Purchase_Count
FROM Customers
GROUP BY item_purchased
ORDER BY Purchase_Count DESC;




--Q4. Which age group shops the most?
SELECT 
    age_group,
    COUNT(*) AS Total_Customers
FROM Customers
GROUP BY age_group
ORDER BY Total_Customers DESC;




--Q5. In which season do we get the highest sales?
SELECT 
    season,
    SUM(purchase_amount) AS Total_Revenue
FROM Customers
GROUP BY season
ORDER BY Total_Revenue DESC;




-- Q6. Which are the top 5 products with the highest average review rating?
SELECT TOP 5
item_purchased,
CAST(ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2)AS DECIMAL(10,2)) AS [Average Product Rating]
FROM Customers
GROUP BY item_purchased
ORDER BY [Average Product Rating] DESC;




--Q7. Which payment method is most used?
SELECT 
    payment_method,
    COUNT(*) AS Usage_Count
FROM Customers
GROUP BY payment_method
ORDER BY Usage_Count DESC;




--Q8. Which shipping type is most used?
SELECT 
    shipping_type,
    COUNT(*) AS shipping_count
FROM Customers
GROUP BY shipping_type
ORDER BY shipping_count DESC;




--Q9. Do discounts drive higher sales?
SELECT 
    discount_applied,
    COUNT(*) AS Total_Orders,
    SUM(purchase_amount) AS Total_Sales
FROM Customers
GROUP BY discount_applied;




--Q10. Segment customers into New, Returning, and Loyal based on their total 
--    number of previous purchases, and show the count of each segment.  
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM Customer)

SELECT customer_segment,count(*) AS number_of_customers
FROM customer_type 
GROUP BY customer_segment




--11. What are the top 3 product inside each category?
SELECT *
FROM
(    SELECT 
        category,
        item_purchased,
        COUNT(*) AS Purchase_Count,
        ROW_NUMBER() OVER 
        (PARTITION BY category 
         ORDER BY COUNT(*) DESC) AS Rank_In_Category
    FROM Customers
    GROUP BY category, item_purchased
) AS RankedData
WHERE Rank_In_Category <= 3;




